### ISSUE TITLE
error from new Quarto: Specifier not found in cache

### ISSUE THREAD

**Issue by kv9898** [quarto-ext/shinylive#65]
For later versions of Quarto (1.6.19 onwards), I got an error which is not present in early versions (1.6.18 and before):

error: Specifier not found in cache: "https://deno.land/std/io/mod.ts", --cached-only is specified.
    at file:///C:/Users/kv989/AppData/Local/shinylive/shinylive/Cache/shinylive-0.7.0/scripts/codeblock-to-json.js:5:27      
Error running filter D:/quarto/share/filters/main.lua:
Error running D:\quarto\bin\quarto.exe (error code 1): <no output>
stack traceback:
        D:\website\_extensions\quarto-ext\shinylive\shinylive.lua:427: in function <D:\website\_extensions\quarto-ext\shinylive\shinylive.lua:408>
        [C]: in ?
        [C]: in method 'walk'
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>
stack traceback:
        D:/quarto/share/filters/main.lua:558: in local 'checked_walk'
        D:/quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
        D:/quarto/share/filters/main.lua:1335: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        D:/quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
        D:/quarto/share/filters/main.lua:1389: in function <D:/quarto/share/filters/main.lua:1386>

**Comment by kv9898** [comment]
Note: a Windows laptop is used.

**Comment by cderv** [comment]
Quarto 1.6 does have breaking change with `quarto run`: prerelease doc has the updated information https://prerelease.quarto.org/docs/projects/scripts.html#deno-scripts

**Comment by kv9898** [comment]
> Quarto 1.6 does have breaking change with `quarto run`: prerelease doc has the updated information https://prerelease.quarto.org/docs/projects/scripts.html#deno-scripts

Thanks for the information. I tried to do a quick fix to bug following the documentation by changing:
```js
import { readLines } from "https://deno.land/std/io/mod.ts";
```
to:
```js
import { readLines } from "stdlib/io";
```

and a new error pops up:
```
error: JSR package version manifest for '@std/io@0.224.9' failed to load: Specifier not found in cache: "https://jsr.io/@std/io/0.224.9_meta.json", --cached-only is specified.
    at file:///C:/Users/kv989/AppData/Local/shinylive/shinylive/Cache/shinylive-0.7.0/scripts/codeblock-to-json.js:5:27
Error running filter D:/quarto/share/filters/main.lua:
```
Any ideas?

**Comment by cderv** [comment]
Something does not seem right... 🤔 I'll dig into that, as I don't think it is related to shinylive.

**Comment by kv9898** [comment]
> Something does not seem right... 🤔 I'll dig into that, as I don't think it is related to shinylive.
> 
> Edit: It seems we have an issue and this is tracked in 
> * https://github.com/quarto-dev/quarto-cli/issues/11219
> 
> Thanks for reporting !

Thank you so much for looking into this. Good to know that both projects belong to Posit and we have someone like you who have worked on both projects. BTW, I want to highlight that this occurs after 1.6.18, I hope this can narrow down the scope of diagnosis.

**Comment by cderv** [comment]
This should be fixed in 1.6.32. You can try again with shinylive and updated scripts.

**Comment by kv9898** [comment]
Somehow I got a new error from 1.6.32:

PS D:\website> quarto preview d:/website/blog/2024-09-27-AutoShinyLiveTheme/index.qmd --no-browser --no-watch-inputs
ERROR: YAML file D:\quarto\share\schema\format-aliases.yml not found.

Stack trace:
    at readYaml (file:///D:/quarto/bin/quarto.js:19569:15)
    at ensureFormats (file:///D:/quarto/bin/quarto.js:40816:31)
    at pandocBuiltInFormats (file:///D:/quarto/bin/quarto.js:40828:5)
    at executionEngineIntermediateFiles (file:///D:/quarto/bin/quarto.js:41440:19)
    at addFile (file:///D:/quarto/bin/quarto.js:80902:37)
    at async Promise.all (index 0)
    at async projectInputFiles (file:///D:/quarto/bin/quarto.js:80941:23)
    at async projectContext (file:///D:/quarto/bin/quarto.js:80648:44)
    at async Command.actionHandler (file:///D:/quarto/bin/quarto.js:107867:25)
    at async Command.execute (file:///D:/quarto/bin/quarto.js:8086:13)

**Comment by cderv** [comment]
> I'm hesitating to write a PR now as I fear the updated script would break support for Quarto 1.5, which is the current stable release?

Yes something needs to be done regarding that... maybe it requires two scripts and use the correct one based on quarto version used ? 

You could probably open a PR with ideas, otherwise we'll come with a solution soon.

**Comment by kv9898** [comment]
> > I'm hesitating to write a PR now as I fear the updated script would break support for Quarto 1.5, which is the current stable release?
> 
> Yes something needs to be done regarding that... maybe it requires two scripts and use the correct one based on quarto version used ?
> 
> You could probably open a PR with ideas, otherwise we'll come with a solution soon.

Very strange, the `codeblock-to-json.js` file is not in this repo or in https://github.com/rstudio/shiny.
